### ISSUE TITLE
[Patch Request] MC-22882 - Cmd + Q closes game instead of drop stack on MacOS

### ISSUE THREAD

**Issue by Madis0** [isXander/Debugify#115]
### Mojang Bug Report ID

MC-22882

### Mod Loader

N/A

### Bug adhere to the guidelines.

- [X] I made sure that this bug adheres to the guidelines.

### Has not already been requested.

- [X] I am certain this patch has not already been requested.

### Has not already been implemented.

- [X] I know that this patch isn't already in the latest version of the mod.

### Example fix implementation

https://www.curseforge.com/minecraft/mc-mods/ctrl-q

**Comment by Cazcez** [comment]
The example implementation mod let us use MacOS's "CONTROL" buton (but equal of Window's control on MacOS is CMD) instead of preventing game to close when we use "CMD + Q". If the patch can prevent game to close the itself on "CMD + Q" shortcut, it would be better than replacing shortcut to "CONTROL + Q"

**Comment by isXander** [comment]
Afaik there is no way to prevent the shell from directly closing an app. Ctrl+Q would be the best.
