### ISSUE TITLE
API for disabling bug fixes

### ISSUE THREAD

**Issue by Gaming32** [isXander/Debugify#192]
It would be nice to be able to disable bugfixes from my mod's own code, so that you don't have to special-case my mod. Can there be an API for this? 

Example: `DebugifyApi#disableBugFix(String bugFix)` would be called like `DebugifyApi.disableBugFix("MC-147605")`.

**Comment by isXander** [comment]
Done! Will appear in the next update.

```java
public class DebugifyIntegration implements DebugifyApi {
    @Override
    public String[] getDisabledFixes() {
        return new String[]{ "MC-147605" };
    }
}
```

Then in your `fabric.mod.json`, add it as an entrypoint for `"debugify"`.

Please be sure to implement `DebugifyApi` in a completely separate class because it will not load on KnotClassLoader but through a mixin plugin. This also means you should not reference any class that can be mixined, because if you do, you prevent every other mod from mixing into that class. **Be careful!**
